export const testobj = {
  payload: {
    source: "PPV",
    departures: [
      {
        direction: "Groningen",
        name: "NS   753",
        plannedDateTime: "2021-02-01T14:33:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:33:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "9",
        actualTrack: "6",
        product: {
          number: "753",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400061",
            mediumName: "Amsterdam Z.",
          },
          {
            uicCode: "8400080",
            mediumName: "Almere C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Dordrecht",
        name: "NS  5055",
        plannedDateTime: "2021-02-01T14:37:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:37:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "2",
        product: {
          number: "5055",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amsterdam Centraal",
        name: "NS  4657",
        plannedDateTime: "2021-02-01T14:38:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:38:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "8",
        product: {
          number: "4657",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400380",
            mediumName: "Laan v NOI",
          },
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400059",
            mediumName: "Sloterdijk",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Tiel",
        name: "NS  6957",
        plannedDateTime: "2021-02-01T14:43:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:43:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "6",
        actualTrack: "4",
        product: {
          number: "6957",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400741",
            mediumName: "Zoetermeer",
          },
          {
            uicCode: "8400258",
            mediumName: "Gouda",
          },
          {
            uicCode: "8400702",
            mediumName: "Woerden",
          },
          {
            uicCode: "8400621",
            mediumName: "Utrecht C.",
          },
        ],
        messages: [
          {
            message:
              "De Intercity van 14:55 naar Enschede is eerder in Utrecht C. en vertrekt van spoor 5",
            style: "INFO",
          },
        ],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amsterdam Centraal",
        name: "NS  2144",
        plannedDateTime: "2021-02-01T14:47:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:47:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "9",
        product: {
          number: "2144",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400302",
            mediumName: "Heemstede-A.",
          },
          {
            uicCode: "8400285",
            mediumName: "Haarlem",
          },
          {
            uicCode: "8400059",
            mediumName: "Sloterdijk",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Eindhoven Centraal",
        name: "NS  1155",
        plannedDateTime: "2021-02-01T14:47:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:47:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "1",
        product: {
          number: "1155",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
          {
            uicCode: "8400131",
            mediumName: "Breda",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Haarlem",
        name: "NS  6342",
        plannedDateTime: "2021-02-01T14:51:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:51:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "7",
        product: {
          number: "6342",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400380",
            mediumName: "Laan v NOI",
          },
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Dordrecht",
        name: "NS  5157",
        plannedDateTime: "2021-02-01T14:54:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:54:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "3",
        product: {
          number: "5157",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Enschede",
        name: "NS  1755",
        plannedDateTime: "2021-02-01T14:55:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:55:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "5",
        product: {
          number: "1755",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400258",
            mediumName: "Gouda",
          },
          {
            uicCode: "8400621",
            mediumName: "Utrecht C.",
          },
          {
            uicCode: "8400055",
            mediumName: "Amersfoort C.",
          },
          {
            uicCode: "8400066",
            mediumName: "Apeldoorn",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Leeuwarden",
        name: "NS  1855",
        plannedDateTime: "2021-02-01T15:03:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:03:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "10",
        product: {
          number: "1855",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400061",
            mediumName: "Amsterdam Z.",
          },
          {
            uicCode: "8400080",
            mediumName: "Almere C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Dordrecht",
        name: "NS  5057",
        plannedDateTime: "2021-02-01T15:07:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:07:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "1",
        product: {
          number: "5057",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amsterdam Centraal",
        name: "NS  4659",
        plannedDateTime: "2021-02-01T15:08:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:08:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "8",
        product: {
          number: "4659",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400380",
            mediumName: "Laan v NOI",
          },
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400059",
            mediumName: "Sloterdijk",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Tiel",
        name: "NS  6959",
        plannedDateTime: "2021-02-01T15:13:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:13:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "6",
        product: {
          number: "6959",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400741",
            mediumName: "Zoetermeer",
          },
          {
            uicCode: "8400258",
            mediumName: "Gouda",
          },
          {
            uicCode: "8400702",
            mediumName: "Woerden",
          },
          {
            uicCode: "8400621",
            mediumName: "Utrecht C.",
          },
        ],
        messages: [
          {
            message:
              "De Intercity van 15:25 naar Schothorst is eerder in Utrecht C. en vertrekt van spoor 5",
            style: "INFO",
          },
        ],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amsterdam Centraal",
        name: "NS  2146",
        plannedDateTime: "2021-02-01T15:17:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:17:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "10",
        product: {
          number: "2146",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400302",
            mediumName: "Heemstede-A.",
          },
          {
            uicCode: "8400285",
            mediumName: "Haarlem",
          },
          {
            uicCode: "8400059",
            mediumName: "Sloterdijk",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Eindhoven Centraal",
        name: "NS  1157",
        plannedDateTime: "2021-02-01T15:17:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:17:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "2",
        product: {
          number: "1157",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
          {
            uicCode: "8400131",
            mediumName: "Breda",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Haarlem",
        name: "NS  6344",
        plannedDateTime: "2021-02-01T15:21:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:21:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "7",
        product: {
          number: "6344",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400380",
            mediumName: "Laan v NOI",
          },
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Dordrecht",
        name: "NS  5159",
        plannedDateTime: "2021-02-01T15:24:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:24:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "3",
        product: {
          number: "5159",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amersfoort Schothorst",
        name: "NS 11757",
        plannedDateTime: "2021-02-01T15:25:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:25:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "5",
        product: {
          number: "11757",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400258",
            mediumName: "Gouda",
          },
          {
            uicCode: "8400621",
            mediumName: "Utrecht C.",
          },
          {
            uicCode: "8400055",
            mediumName: "Amersfoort C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Groningen",
        name: "NS   757",
        plannedDateTime: "2021-02-01T15:33:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:33:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "9",
        product: {
          number: "757",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400061",
            mediumName: "Amsterdam Z.",
          },
          {
            uicCode: "8400080",
            mediumName: "Almere C.",
          },
        ],
        messages: [
          {
            message: "Treinstel 4030 rijdt niet verder dan Zwolle",
            style: "INFO",
          },
        ],
        departureStatus: "INCOMING",
      },
    ],
  },
};

export const failureScenario = {
  payload: {
    source: "PPV",
    departures: [
      {
        direction: "Groningen",
        name: "NS   753",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:33:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "9",
        actualTrack: "6",
        product: {
          number: "753",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400061",
            mediumName: "Amsterdam Z.",
          },
          {
            uicCode: "8400080",
            mediumName: "Almere C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Dordrecht",
        name: "NS  5055",
        plannedDateTime: "2021-02-01T14:37:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:37:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "2",
        product: {
          number: "5055",
          // categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amsterdam Centraal",
        name: "NS  4657",
        plannedDateTime: "2021-02-01T14:38:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:38:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "8",
        product: {
          number: "4657",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400380",
            mediumName: "Laan v NOI",
          },
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400059",
            mediumName: "Sloterdijk",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Tiel",
        name: "NS  6957",
        plannedDateTime: "2021-02-01T14:43:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:43:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "6",
        actualTrack: "4",
        product: {
          number: "6957",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400741",
            mediumName: "Zoetermeer",
          },
          {
            uicCode: "8400258",
            mediumName: "Gouda",
          },
          {
            uicCode: "8400702",
            mediumName: "Woerden",
          },
          {
            uicCode: "8400621",
            mediumName: "Utrecht C.",
          },
        ],
        messages: [
          {
            message:
              "De Intercity van 14:55 naar Enschede is eerder in Utrecht C. en vertrekt van spoor 5",
            style: "INFO",
          },
        ],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amsterdam Centraal",
        name: "NS  2144",
        plannedDateTime: "2021-02-01T14:47:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:47:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "9",
        product: {
          number: "2144",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400302",
            mediumName: "Heemstede-A.",
          },
          {
            uicCode: "8400285",
            mediumName: "Haarlem",
          },
          {
            uicCode: "8400059",
            mediumName: "Sloterdijk",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Eindhoven Centraal",
        name: "NS  1155",
        plannedDateTime: "2021-02-01T14:47:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:47:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "1",
        product: {
          number: "1155",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
          {
            uicCode: "8400131",
            mediumName: "Breda",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Haarlem",
        name: "NS  6342",
        plannedDateTime: "2021-02-01T14:51:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:51:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "7",
        product: {
          number: "6342",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400380",
            mediumName: "Laan v NOI",
          },
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Dordrecht",
        name: "NS  5157",
        plannedDateTime: "2021-02-01T14:54:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:54:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "3",
        product: {
          number: "5157",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Enschede",
        name: "NS  1755",
        plannedDateTime: "2021-02-01T14:55:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T14:55:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "5",
        product: {
          number: "1755",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400258",
            mediumName: "Gouda",
          },
          {
            uicCode: "8400621",
            mediumName: "Utrecht C.",
          },
          {
            uicCode: "8400055",
            mediumName: "Amersfoort C.",
          },
          {
            uicCode: "8400066",
            mediumName: "Apeldoorn",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Leeuwarden",
        name: "NS  1855",
        plannedDateTime: "2021-02-01T15:03:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:03:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "10",
        product: {
          number: "1855",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400061",
            mediumName: "Amsterdam Z.",
          },
          {
            uicCode: "8400080",
            mediumName: "Almere C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Dordrecht",
        name: "NS  5057",
        plannedDateTime: "2021-02-01T15:07:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:07:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "1",
        product: {
          number: "5057",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amsterdam Centraal",
        name: "NS  4659",
        plannedDateTime: "2021-02-01T15:08:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:08:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "8",
        product: {
          number: "4659",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400380",
            mediumName: "Laan v NOI",
          },
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400059",
            mediumName: "Sloterdijk",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Tiel",
        name: "NS  6959",
        plannedDateTime: "2021-02-01T15:13:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:13:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "6",
        product: {
          number: "6959",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400741",
            mediumName: "Zoetermeer",
          },
          {
            uicCode: "8400258",
            mediumName: "Gouda",
          },
          {
            uicCode: "8400702",
            mediumName: "Woerden",
          },
          {
            uicCode: "8400621",
            mediumName: "Utrecht C.",
          },
        ],
        messages: [
          {
            message:
              "De Intercity van 15:25 naar Schothorst is eerder in Utrecht C. en vertrekt van spoor 5",
            style: "INFO",
          },
        ],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amsterdam Centraal",
        name: "NS  2146",
        plannedDateTime: "2021-02-01T15:17:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:17:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "10",
        product: {
          number: "2146",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400302",
            mediumName: "Heemstede-A.",
          },
          {
            uicCode: "8400285",
            mediumName: "Haarlem",
          },
          {
            uicCode: "8400059",
            mediumName: "Sloterdijk",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Eindhoven Centraal",
        name: "NS  1157",
        plannedDateTime: "2021-02-01T15:17:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:17:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "2",
        product: {
          number: "1157",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
          {
            uicCode: "8400131",
            mediumName: "Breda",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Haarlem",
        name: "NS  6344",
        plannedDateTime: "2021-02-01T15:21:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:21:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "7",
        product: {
          number: "6344",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400380",
            mediumName: "Laan v NOI",
          },
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Dordrecht",
        name: "NS  5159",
        plannedDateTime: "2021-02-01T15:24:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:24:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "3",
        product: {
          number: "5159",
          categoryCode: "SPR",
          shortCategoryName: "NS Sprinter",
          longCategoryName: "Sprinter",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "SPR",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400280",
            mediumName: "Den Haag HS",
          },
          {
            uicCode: "8400170",
            mediumName: "Delft",
          },
          {
            uicCode: "8400530",
            mediumName: "Rotterdam C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Amersfoort Schothorst",
        name: "NS 11757",
        plannedDateTime: "2021-02-01T15:25:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:25:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "5",
        product: {
          number: "11757",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400258",
            mediumName: "Gouda",
          },
          {
            uicCode: "8400621",
            mediumName: "Utrecht C.",
          },
          {
            uicCode: "8400055",
            mediumName: "Amersfoort C.",
          },
        ],
        messages: [],
        departureStatus: "INCOMING",
      },
      {
        direction: "Groningen",
        name: "NS   757",
        plannedDateTime: "2021-02-01T15:33:00+0100",
        plannedTimeZoneOffset: 60,
        actualDateTime: "2021-02-01T15:33:00+0100",
        actualTimeZoneOffset: 60,
        plannedTrack: "9",
        product: {
          number: "757",
          categoryCode: "IC",
          shortCategoryName: "NS Intercity",
          longCategoryName: "Intercity",
          operatorCode: "NS",
          operatorName: "NS",
          type: "TRAIN",
        },
        trainCategory: "IC",
        cancelled: false,
        routeStations: [
          {
            uicCode: "8400390",
            mediumName: "Leiden C.",
          },
          {
            uicCode: "8400561",
            mediumName: "Schiphol Airport",
          },
          {
            uicCode: "8400061",
            mediumName: "Amsterdam Z.",
          },
          {
            uicCode: "8400080",
            mediumName: "Almere C.",
          },
        ],
        messages: [
          {
            message: "Treinstel 4030 rijdt niet verder dan Zwolle",
            style: "INFO",
          },
        ],
        departureStatus: "INCOMING",
      },
    ],
  },
};
